"""create core tables

Revision ID: 02e4fae3f50b
Revises: 
Create Date: 2025-12-30 23:03:25.848870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02e4fae3f50b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('gmail_account_email', sa.String(length=320), nullable=False),
    sa.Column('gmail_last_history_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gmail_account_email')
    )
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('algo_version', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_user_day', 'clusters', ['user_id', 'digest_date'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('gmail', 'json', name='channel_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', 'external_id', name='uq_thread_user_channel_external')
    )
    op.create_index('ix_thread_user_channel', 'threads', ['user_id', 'channel'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('gmail', 'json', name='channel_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('thread_external_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('snippet', sa.String(length=2048), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('history_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('inbox', 'archived', 'snoozed', 'deleted', name='message_status_enum'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', 'external_id', name='uq_message_user_channel_external')
    )
    op.create_index('ix_message_user_status', 'messages', ['user_id', 'status'], unique=False)
    op.create_index('ix_message_user_timestamp', 'messages', ['user_id', 'timestamp'], unique=False)
    op.create_table('suggested_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('archive_all', 'snooze', 'reply_with_template', 'label_add', 'label_remove', name='action_type_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', name='urgency_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'rejected', name='suggestion_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suggested_actions_user_cluster', 'suggested_actions', ['user_id', 'cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suggested_actions_user_cluster', table_name='suggested_actions')
    op.drop_table('suggested_actions')
    op.drop_index('ix_message_user_timestamp', table_name='messages')
    op.drop_index('ix_message_user_status', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_thread_user_channel', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_cluster_user_day', table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('users')
    # ### end Alembic commands ###
